#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <enclave_manager_icons.h>

int32_t enclave_manager_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm enclave_manager!");

    return 0;
}
